# Generated by Django 5.0.1 on 2024-01-13 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('category', models.CharField(choices=[('s', 'Смартфон'), ('l', 'Ноутбук'), ('g', 'Видеокарта')], max_length=1, verbose_name='Категория')),
                ('description', models.TextField(max_length=100, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='media', verbose_name='Картинка')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1500, verbose_name='Текст отзыва')),
                ('rate', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка')),
                ('moderate', models.BooleanField(default=False, verbose_name='Модерация')),
                ('date_add', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('date_edit', models.DateField(auto_now=True, verbose_name='Дата редактирования')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a_review', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_review', to='products.products', verbose_name='Продукт')),
            ],
        ),
    ]
