# Generated by Django 5.0.1 on 2024-01-15 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_review_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'permissions': [('edit_prod', 'Редактировать товар'), ('delete_prod', 'Удалить товар'), ('create_prod', 'Добавить товар')]},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': [('edit_rev', 'Редактировать отзыв'), ('delete_rev', 'Удалить отзыв'), ('create_rev', 'Создать отзыв'), ('moderate_rev', 'Модерация отзывов')]},
        ),
    ]
